version: '3.9'

x-cassandra-parameters: &cassandra-parameters
  image: cassandra:latest
  environment:
    - CASSANDRA_CLUSTER_NAME=MyCluster
    - NUM_TOKENS=3
    - DS_LINSE=accept
    - RACK=RAC1
    - MAX_HEAP_SIZE=512M
    - HEAP_NEWSIZE=200M
    - START_RPC=true
  expose:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9142
  networks:
    - cassandra_net
  ulimits:
    memlock: -1
    nproc: 8192
  deploy:
    resources:
      limits:
        memory: 4G
        cpus: '0.5'
  healthcheck:
    test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
    interval: 30s
    timeout: 20s
    retries: 3
  volumes:
    - cassandra-data:/var/lib/cassandra

services:
  cassandra1:
    <<: *cassandra-parameters
    container_name: cassandra1
    networks:
      cassandra_net:
        ipv4_address: 192.168.2.200
    hostname: cassandra1
    ports:
      - "9042:9042"
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9142:9142"
    environment:
      - DC=DC1
      - CASSANDRA_SEEDS=192.168.0.145
      - CASSANDRA_LISTEN_ADDRESS=192.168.2.200
      - CASSANDRA_BROADCAST_ADDRESS=192.168.0.145
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=192.168.0.145

  cassandra2:
    <<: *cassandra-parameters
    container_name: cassandra2
    networks:
      cassandra_net:
        ipv4_address: 192.168.2.201
    hostname: cassandra2
    ports:
      - "9043:9042"
      - "7002:7000"
      - "7003:7001"
      - "7200:7199"
      - "9143:9142"
    environment:
#      - CASSANDRA_SEEDS=cassandra1, cassandra2
      - DC=DC2
      - CASSANDRA_SEEDS=192.168.0.145
      - CASSANDRA_LISTEN_ADDRESS=192.168.2.201
      - CASSANDRA_BROADCAST_ADDRESS=192.168.0.145
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=192.168.0.145
    depends_on:
      - cassandra1

  cassandra3:
    <<: *cassandra-parameters
    container_name: cassandra3
    networks:
      cassandra_net:
        ipv4_address: 192.168.2.202
    hostname: cassandra3
    ports:
      - "9044:9042"
      - "7004:7000"
      - "7005:7001"
      - "7201:7199"
      - "9144:9142"
    environment:
#      - CASSANDRA_SEEDS=cassandra1, cassandra3
      - DC=DC2
      - CASSANDRA_SEEDS=192.168.0.145
      - CASSANDRA_LISTEN_ADDRESS=192.168.2.202
      - CASSANDRA_BROADCAST_ADDRESS=192.168.0.145
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=192.168.0.145
    depends_on:
      - cassandra1
      - cassandra2

networks:
  cassandra_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24

volumes:
  cassandra-data: