version: '3.9'

x-cassandra-parameters: &cassandra-parameters
  image: cassandra:latest
  environment:
    - CASSANDRA_SEEDS=cassandra1
    - CASSANDRA_CLUSTER_NAME=MyCluster
    - NUM_TOKENS=3
    - DC=DC1
    - DS_LINSE=accept
    - RACK=RAC1
    - MAX_HEAP_SIZE=1G
    - HEAP_NEWSIZE=200M
    - START_RPC=false
  expose:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9142
  networks:
    cassandra_net:
      ipv4_address:
  ulimits:
    memlock: -1
    nproc: 32768
  deploy:
    resources:
      limits:
        memory: 4G
        cpus: '0.5'
  healthcheck:
    test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  cassandra1:
    <<: *cassandra-parameters
    image: cassandra:latest
    container_name: cassandra1
    networks:
      cassandra_net:
        ipv4_address: 192.168.1.200
    hostname: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - DC=DC1

  cassandra2:
    <<: *cassandra-parameters
    image: cassandra:latest
    container_name: cassandra2
    networks:
      cassandra_net:
        ipv4_address: 192.168.1.201
    hostname: cassandra2
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1, cassandra2
      - DC=DC2
    depends_on:
      - cassandra1

  cassandra3:
    <<: *cassandra-parameters
    image: cassandra:latest
    container_name: cassandra3
    networks:
      cassandra_net:
        ipv4_address: 192.168.1.202
    hostname: cassandra3
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1, cassandra3
      - DC=DC2
    depends_on:
      - cassandra1
      - cassandra2

networks:
  cassandra_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24