name: test

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Upgrade pip, setuptools, and wheel
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          pip install --upgrade wheel

      - name: Install Cython
        run: pip install cython

      - name: Install system dependencies
        run: sudo apt-get install -y gcc python3-dev

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Linting
        run: flake8 --exclude .venv